find_package(BoostFusion)
find_package(METIS)
find_package(ParMETIS)
include(AddParMETISFlags)
find_package(SuperLU)
include(AddSuperLUFlags)
find_package(UMFPack)
include(AddUMFPackFlags)

include(TestBigEndian)
test_big_endian(BIGENDIAN)
if(BIGENDIAN)
  add_definitions(-DHAVE_BIGENDIAN)
endif(BIGENDIAN)
